# Generated by Django 5.2.17 on 2026-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="question",
            name="skill",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
